apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-user # The name of the secret
  annotations:
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: *****
  password: *****
